[project]
name = "therapy_multi"
version = "0.1.0"
description = "Therapy-Multi using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.12.2"
]

[project.scripts]
therapy_multi = "therapy_multi.main:run"
run_crew = "therapy_multi.main:run"
train = "therapy_multi.main:train"
replay = "therapy_multi.main:replay"
test = "therapy_multi.main:test"
run_with_trigger = "therapy_multi.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
